/// <reference types="nativewind/types" />
 
// NOTE: This file should not be edited and should be committed with your source code. It is generated by NativeWind. If you need to move or disable this file, please see the documentation.